version: '2'
services:
  spree_db:
    ports:
      - '5433:5432'
    image: postgres
    volumes:
      - /tmp/spree-postgres-data:/var/lib/postgresql/data
  db:
    ports:
      - '5432:5432'
    image: postgres
    volumes:
      - /tmp/data-sync-postgres-data:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/data-sync
    ports:
      - "3000:3000"
    depends_on:
      - db
      - spree_db
